edition = "2024"

fn_single_line = true
reorder_modules = true
reorder_imports = true
group_imports = "Preserve"
fn_params_layout = "Compressed"
use_small_heuristics = "Max"
remove_nested_parens = true
use_field_init_shorthand = true
condense_wildcard_suffixes = true

max_width = 120
array_width = 120
chain_width = 120
fn_call_width = 120
struct_lit_width = 120
attr_fn_like_width = 120
struct_variant_width = 120
single_line_if_else_max_width = 120
single_line_let_else_max_width = 120
short_array_element_width_threshold = 120
